### ISSUE TITLE
Checkbox: Kit delivered

### ISSUE THREAD

**Issue by Llediarth** [roxlukas/lmeve#20]
It would be great to have checkbox to mark Kits as delivered (to POS).

It would help to improve the logistical overview and also help the fight 'corp-assets in private use'.

**Comment by roxlukas** [comment]
Where do you want to display it? At facility level? Or at individual task level?
I assume this box will have to re-set at the end of the month?

**Comment by Llediarth** [comment]
1.) It should be displayed in the task view and in view all tasks.

2.) I suggest individual task level. Facility would really help for sorting out which task is missing etc.

3.) Same behavior as tasks in general. Reset at the end of the month except 1-Time-Tasks (and maybe only for tasks that have been produced something).
