### ISSUE TITLE
Trouble with Skins.php

### ISSUE THREAD

**Issue by ConteoSL** [roxlukas/lmeve#23]
Hi.
After upgrading to the latest version i got an error (see attachment).
![error](https://cloud.githubusercontent.com/assets/14912826/10203640/f0be41ec-67bf-11e5-9eab-026cd6be633c.png)
The problem was in file include/skins.php at lines 9 and 66.
I replace "skinMaterialsRGB" to "skinMaterials" and that's ok.
And another one. Latest SDE (Vanguard) does not contain file "skinMaterialSets.yaml". Need to fix yaml_updater i think.
Thx.

**Comment by roxlukas** [comment]
Hi,

Thanks for the report. Yeah, the file skinMaterialSets.yaml doesn't exist in SDE, *YET*. I spoke to CCP on #devfleet Slack about it, and there is a chance they will include it in one of the next versions of SDE (the file was supposed to exist already, hence the support for it in LMeve).

I will make some fallback mechanism until CCP includes the file in dump.

**Comment by roxlukas** [comment]
fixed in 1dd935ef33
