### ISSUE TITLE
Issue bringing in YAML files

### ISSUE THREAD

**Issue by Hightech1011** [roxlukas/lmeve#24]
I get the following error when trying to run "php ./bin/update_yaml.php --all"

Calling updateYamlTypeIDs(), please wait... File ../data/devdeeps_eveSDE/typeIDs.yaml does not exist. Make sure YAML files from EVE SDE are in appropriate directories.done
Calling updateYamlGraphicIDs(), please wait... File ../data/devdeeps_eveSDE/graphicIDs.yaml does not exist. Make sure YAML files from EVE SDE are in appropriate directories.done
Calling updateYamlCertificates(), please wait... File ../data/devdeeps_eveSDE/certificates.yaml does not exist. Make sure YAML files from EVE SDE are in appropriate directories.done
Calling updateYamlBlueprints(), please wait... File ../data/devdeeps_eveSDE/blueprints.yaml does not exist. Make sure YAML files from EVE SDE are in appropriate directories.done
Calling recreateLegacyTables(), please wait... <br><table class="error"><tr><td>Database error. Contact your administrator and report the problem.<br/></td></tr></table><input type="button" value="&lt; Back" onclick="history.back();">

The files do exist:

# ls -lah ./data/devdeeps_eveSDE/
total 63M
drwxr-xr-x 2 devdeeps devdeeps 4.0K Mar 11 04:48 ./
drwxr-xr-x 4 devdeeps devdeeps 4.0K Mar 11 04:34 ../
-rw-r--r-- 1 devdeeps devdeeps 4.2M Mar  9 10:24 blueprints.yaml
-rw-r--r-- 1 devdeeps devdeeps 8.4K Mar  9 10:25 categoryIDs.yaml
-rw-r--r-- 1 devdeeps devdeeps 193K Mar  9 10:25 certificates.yaml
-rw-r--r-- 1 devdeeps devdeeps 397K Mar  9 10:25 graphicIDs.yaml
-rw-r--r-- 1 devdeeps devdeeps 534K Mar  9 10:25 groupIDs.yaml
-rw-r--r-- 1 devdeeps devdeeps 237K Mar  9 10:25 iconIDs.yaml
-rw-r--r-- 1 devdeeps devdeeps 309K Mar  9 10:25 skinLicenses.yaml
-rw-r--r-- 1 devdeeps devdeeps 5.0K Mar  9 10:25 skinMaterials.yaml
-rw-r--r-- 1 devdeeps devdeeps 298K Mar  9 10:25 skins.yaml
-rw-r--r-- 1 devdeeps devdeeps 7.3K Mar  9 10:25 tournamentRuleSets.yaml
-rw-r--r-- 1 devdeeps devdeeps  57M Mar  9 10:25 typeIDs.yaml

Suggestions?

**Comment by roxlukas** [comment]
Hi,

Try running update_yaml.php from bin directory, rather then from lmeve top directory:

```
cd bin
php update_yaml.php --all
```

I'll try to fix it in the next release by using full file paths (dirname(__FILE__).'path/to/file') instead of relative paths

**Comment by Hightech1011** [comment]
That worked, however a new error pops up when trying to load the YAML files:

Calling updateYamlTypeIDs(), please wait... loading YAML...insert to DB...done
Calling updateYamlGraphicIDs(), please wait... loading YAML...insert to DB...done
Calling updateYamlCertificates(), please wait... insert to DB...done
Calling updateYamlBlueprints(), please wait... loading YAML...insert to DB...done
Calling recreateLegacyTables(), please wait... <br><table class="error"><tr><td>Database error. Contact your administrator and report the problem.<br/></td></tr></table><input type="button" value="&lt; Back" onclick="history.back();"

**Comment by roxlukas** [comment]
Could you go to **lmeve/var/** directory and check the last lines in **error.txt** ?

**Comment by Hightech1011** [comment]
Last entry in "error.txt":

<b>15.03.2016 3:53:46 [CLI]:</b> Error in query: INSERT INTO `devdeeps_eveSDE`.`ramTypeRequirements`      
    SELECT DISTINCT ybp.`productTypeID` AS `typeID`,
        ybp.`activityID`,
        ybm.`materialTypeID` AS `requiredTypeID`,
        ybm.`quantity`,
        ybm.`consume` AS `damagePerJob`,
        ybm.`consume` AS `recycle`
    FROM `devdeeps_eveSDE`.`yamlBlueprintProducts` ybp
    JOIN `devdeeps_eveSDE`.`yamlBlueprintMaterials` ybm
    ON ybp.`blueprintTypeID`=ybm.`blueprintTypeID` AND ybp.`activityID`=ybm.`activityID`; MySQL reply: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '21527-1-34' for key 'PRIMARY'<br>

**Comment by roxlukas** [comment]
There has been some changes in blueprints.yaml between yc118-2 and yc118-3 regarding typeID=21527 ('Firewall' Signal Amplifier). In yc118-2 there is just 1 blueprint which produces this item (typeID 21528):

`21528:
    activities:
        copying:
            time: 720
        manufacturing:
            materials:
            -   quantity: 1010
                typeID: 34
            -   quantity: 267
                typeID: 35
            -   quantity: 2
                typeID: 21572
            -   quantity: 1
                typeID: 20110
            -   quantity: 1
                typeID: 21584
            -   quantity: 1
                typeID: 21585
            -   quantity: 738
                typeID: 36
            -   quantity: 3
                typeID: 21722
            products:
            -   quantity: 1
                typeID: 21527
            skills:
            -   level: 5
                typeID: 3380
            -   level: 2
                typeID: 21789
            time: 900
        research_material:
            time: 315
        research_time:
            time: 315
    blueprintTypeID: 21528
    maxProductionLimit: 200`

However in yc118-3 there is 4 blueprints which produce the same item:

`21522:
    activities:
        copying:
            time: 720
        manufacturing:
            materials:
            -   quantity: 1
                typeID: 20110
            -   quantity: 1
                typeID: 21584
            -   quantity: 2
                typeID: 21572
            -   quantity: 3
                typeID: 21722
            -   quantity: 143
                typeID: 35
            -   quantity: 249
                typeID: 36
            -   quantity: 2386
                typeID: 34
            products:
            -   quantity: 1
                typeID: 21527
            skills:
            -   level: 2
                typeID: 21789
            -   level: 5
                typeID: 3380
            time: 900
        research_material:
            time: 315
        research_time:
            time: 315
    blueprintTypeID: 21522
    maxProductionLimit: 200

21524:
    activities:
        copying:
            time: 720
        manufacturing:
            materials:
            -   quantity: 1
                typeID: 20110
            -   quantity: 1
                typeID: 21584
            -   quantity: 2
                typeID: 21572
            -   quantity: 3
                typeID: 21722
            -   quantity: 143
                typeID: 35
            -   quantity: 249
                typeID: 36
            -   quantity: 2386
                typeID: 34
            products:
            -   quantity: 1
                typeID: 21527
            skills:
            -   level: 2
                typeID: 21789
            -   level: 5
                typeID: 3380
            time: 900
        research_material:
            time: 315
        research_time:
            time: 315
    blueprintTypeID: 21524
    maxProductionLimit: 200

21526:
    activities:
        copying:
            time: 720
        manufacturing:
            materials:
            -   quantity: 1
                typeID: 20110
            -   quantity: 1
                typeID: 21584
            -   quantity: 2
                typeID: 21572
            -   quantity: 3
                typeID: 21722
            -   quantity: 143
                typeID: 35
            -   quantity: 249
                typeID: 36
            -   quantity: 2386
                typeID: 34
            products:
            -   quantity: 1
                typeID: 21527
            skills:
            -   level: 2
                typeID: 21789
            -   level: 5
                typeID: 3380
            time: 900
        research_material:
            time: 315
        research_time:
            time: 315
    blueprintTypeID: 21526
    maxProductionLimit: 200

21528:
    activities:
        copying:
            time: 720
        manufacturing:
            materials:
            -   quantity: 1010
                typeID: 34
            -   quantity: 267
                typeID: 35
            -   quantity: 2
                typeID: 21572
            -   quantity: 1
                typeID: 20110
            -   quantity: 1
                typeID: 21584
            -   quantity: 1
                typeID: 21585
            -   quantity: 738
                typeID: 36
            -   quantity: 3
                typeID: 21722
            products:
            -   quantity: 1
                typeID: 21527
            skills:
            -   level: 5
                typeID: 3380
            -   level: 2
                typeID: 21789
            time: 900
        research_material:
            time: 315
        research_time:
            time: 315
    blueprintTypeID: 21528
    maxProductionLimit: 200

21530:
    activities:
        copying:
            time: 720
        manufacturing:
            materials:
            -   quantity: 1
                typeID: 20110
            -   quantity: 1
                typeID: 21073
            -   quantity: 1
                typeID: 21584
            -   quantity: 1
                typeID: 21585
            -   quantity: 3
                typeID: 21572
            -   quantity: 4
                typeID: 21722
            -   quantity: 143
                typeID: 35
            -   quantity: 249
                typeID: 36
            -   quantity: 2386
                typeID: 34
            products:
            -   quantity: 1
                typeID: 21527
            skills:
            -   level: 2
                typeID: 21789
            -   level: 5
                typeID: 3380
            time: 900
        research_material:
            time: 315
        research_time:
            time: 315
    blueprintTypeID: 21530
    maxProductionLimit: 200`

I assumed 1 blueprint - 1 item matching, so I can tell materials required by an item. In this case I won't be able to tell material list, because each bleuprint has different material lists and they all produce the very same item.

As a workaround I can use "INSERT IGNORE" in yaml loader, which will silently fail when encountering such problem, but it will mean only one bleuprint will work in LMeve and the others will have empty material lists.

**Comment by roxlukas** [comment]
Workaround in 8647a49

**Comment by roxlukas** [comment]
According to CCP FoxFour this is most likely a bug in SDE, please open a Bug Report for this issue on https://bugs.eve-online.com/ and paste the BR# number here, so @Regner can investigate it.
