### ISSUE TITLE
Citadel SDE breaks invBlueprintTypes table

### ISSUE THREAD

**Issue by Wildweasel24** [roxlukas/lmeve#26]
Hi Lukas,

Did a clean install from latest source here, into Debian.

Imported latest Steve Ronuken Mysql sde conversion as of 2nd May.

Task creations, database lookups, profit explorer etc starting showing missing data problems.

Traced issues to invBlueprintTypes table have several missing field values.

Created manual SQL script below to update missing values from SDE tables.

CO

`-- Name of $LM_EVEDB
USE eve_sde ;

-- Update Blueprint Products
UPDATE invBlueprintTypes as s
inner join industryActivityProducts as g  on s.blueprintTypeID = g.typeID
SET 
s.productTypeID = g.productTypeID
where g.activityID = 1 ;

-- Update Manufacturing Time
UPDATE invBlueprintTypes as s
inner join industryActivity as g  on s.blueprintTypeID = g.typeID
SET 
s.productiontime = g.time
where g.activityID = 1 ;

-- Update TE Time
UPDATE invBlueprintTypes as s
inner join industryActivity as g  on s.blueprintTypeID = g.typeID
#Inner join invTypes as i on s.blueprintTypeID = i.typeID
SET 
s.researchProductivityTime = g.time
where g.activityID = 3 ;

-- Update ME Time
UPDATE invBlueprintTypes as s
inner join industryActivity as g  on s.blueprintTypeID = g.typeID
SET 
s.researchMaterialTime = g.time
where g.activityID = 4 ;

-- Update COPY Time
UPDATE invBlueprintTypes as s
inner join industryActivity as g  on s.blueprintTypeID = g.typeID
SET 
s.researchCopyTime = g.time
where g.activityID = 5 ;

-- Update INVENTION Time
UPDATE invBlueprintTypes as s
inner join industryActivity as g  on s.blueprintTypeID = g.typeID
SET 
s.researchTechTime = g.time
where g.activityID = 8 ;

-- Update Blueprint T2 ParentBPO
UPDATE invBlueprintTypes as s
inner join industryActivityProducts as g  on s.blueprintTypeID = g.productTypeID
SET 
s.parentBlueprintTypeID = g.TypeID
where g.activityID = 8 ;

-- Update INCORRECT TECH LEVELS
UPDATE invBlueprintTypes as s
inner join invTypes as i on blueprintTypeID = i.typeID
SET 
s.techLevel = 2
where techLevel = 1 and parentBlueprintTypeID IS NOT NULL and i.published = 1;`

**Comment by roxlukas** [comment]
Thanks for the bug report. I was testing on an already working instance, so might have missed something that would only surface in a brand new install.

**Comment by roxlukas** [comment]
Could you please send me /var/error.txt to my e-mail? It contains SQL errors which will possibly reveal why the table invBlueprintTypes was incomplete.

**Comment by Wildweasel24** [comment]
[LMEVE_DIR]/var/error.txt - no such file

**Comment by Wildweasel24** [comment]
closed by mistake

**Comment by roxlukas** [comment]
I will run a clean install on Debian and see if I can reproduce it.

2016-05-16 18:22 GMT+02:00 Wildweasel24 <notifications@github.com>:

**Comment by roxlukas** [comment]
Hi,

Please do the following (assuming lmeve is under /opt/lmeve)

  * Make sure you're logged out of LMeve.

  * Add permissions to log directory so webserver can write to it
`chown -R root:www-data /opt/lmeve/var/`
`chmod -R g+w /opt/lmeve/var/`

  * re-import SDE

`mysql -u root -p`
`DROP DATABASE eve_sde`
`CREATE DATABASE eve_sde`
`USE eve_sde`
`\. sde-20160429-TRANQUILITY-2.sql` make sure you have the MySQL SDE file in path

  * log in to LMeve

This should cause all the missing tables to be recreated. I've added some additional sanity checks in dbcatalog, so if you still have problems aftere following the above instruction, please update your LMeve with the most recent commit.

**Comment by Wildweasel24** [comment]
Followed your instructions, logged in..

Went to database, lookup Amarr Shuttle for example:


Error in query: SELECT shp.*,skn.*,mat.*,lic.* FROM eve_sde.`skinShip` shp JOIN eve_sde.`skins` skn ON shp.`skinID` = skn.`skinID` LEFT JOIN eve_sde.`skinMaterialsRGB` mat ON skn.`skinMaterialID` = mat.`skinMaterialID` JOIN eve_sde.`skinLicense` lic ON lic.`skinID` = skn.`skinID` JOIN eve_sde.`invTypes` itp ON lic.`licenseTypeID`=itp.`typeID` WHERE shp.`typeID` = 11134 AND duration=-1
MySQL reply: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eve_sde.skinMaterialsRGB' doesn't exist

Will update to latest commit & reimport SDE.

**Comment by roxlukas** [comment]
I hadexactly the same happening during my test Debian install. Latest
commit should resolve this one.

2016-05-18 15:30 GMT+02:00 Wildweasel24 <notifications@github.com>:

**Comment by Wildweasel24** [comment]
All working perfectly ok now.

Absolutely required the "pecl install yaml" step,  which requires you to install php-pear, php5-dev and yaml-dev dependencies in Debian.  

NB yaml-dev is not automatically pulled in as a dependency, but without it the "pecl install.." step fails though missing header files.
