### ISSUE TITLE
Include TCU fuel bonus in POS Fuel calculations

### ISSUE THREAD

**Issue by roxlukas** [roxlukas/lmeve#28]
- Must add /sovereignty/structures/ endpoint from CREST first
- Then for each Control Tower in LMeve database must check it the parent alliance owns TCU in the same system where the POS is located. If so, include 25% fuel bonus in calculations.

originally sent by ClaasStoertenbecker

**Comment by roxlukas** [comment]
**IMPORTANT INFORMATION** My dev laptop has recently suffered a hardware failure*, and because of very tight budget I won't be able to replace it anytime soon. Due to the above fixes will be delayed, but rest assured I haven't given up on LMeve yet.

*) Most likely GPU or Northbridge went up in smoke

**Comment by Commissar0617** [comment]
IMO, why add features to something that will soon be depreciated

**Comment by roxlukas** [comment]
Agreed, focusing on ESI right now.

Pozdrawiam serdecznie,
Łukasz Poźniak

**Comment by roxlukas** [comment]
Since Starbases are going to be phased out, this enhancement makes little sense.
