### ISSUE TITLE
POS Silos

### ISSUE THREAD

**Issue by ClaasStoertenbecker** [roxlukas/lmeve#29]
An awesome feature would be a popup information for space left in silos like the notification for the pos fuel.

**Comment by roxlukas** [comment]
At what percentage level do you think the notification should show?

**Comment by ClaasStoertenbecker** [comment]
I think it would be the best if you calculate at what rate the silo is filling so that you can show for every silo a warning if less than 2 days are left until it is full

**Comment by roxlukas** [comment]
Unfortunately I do not store inventory changes over time, so I can't tell at what rate the silos fill. I also do not have information what is connected to a specific silo. 

Therefore I will add a configurable percentage at which silo notifications pop up.

**Comment by roxlukas** [comment]
Included in the upcoming patch

**Comment by roxlukas** [comment]
Added in d132dd5
