### ISSUE TITLE
Enhancement Suggestion - Table crestindustrysystems

### ISSUE THREAD

**Issue by Wildweasel24** [roxlukas/lmeve#30]
costIndex field is currently Decimal(20,2), suggest change to Decimal(20,4)
 
Currently truncates all values 0.0100 to 0.0199 as 0.01.

Represents 1.00% - 1.99%  stored as 1%

Therefore cost calculations incorrect by up to factor of 100% in example above.

**Comment by roxlukas** [comment]
Included in the upcoming patch

**Comment by roxlukas** [comment]
Added in d132dd5
