### ISSUE TITLE
Choose what silos to display and show on which POS they are anchored

### ISSUE THREAD

**Issue by clstb** [roxlukas/lmeve#34]
Station inventory works fine now.
Created tasks have the right time now.
Silos are displayed properly.

Enhancement:
Choose what silos to display and show on which POS they are anchored.

**Comment by roxlukas** [comment]
This is planned. Also Gallente Towers give 100% bonus to capacity, and I'd like to include it in notifications. Unfortunately I don't have data or API Keys to work with, so it's been delayed. Help in that regard will be much appreciated.

**Comment by ClaasStoertenbecker** [comment]
That is no problem, im surely willing to help. Write an email to claas.stoertenbecker@web.de and tell me what you need. Im running the current version of the LMEVE for my corporation on a vserver if that is interesting for you.

**Comment by roxlukas** [comment]
I will need dumps of the following tables:

- apiassets
- apistarbaselist
- apistarbasedetails
- apilocations

apiassets contains list of all corp assets, including POS Structures (we
need silos)
apistarbaselist and apistarbasedetails contain information about control
towers and their types
apilocations contains x,y,z coordinates which allow distance calculation
between silos and control towers.

PS the same distance calculation is already done to match labs to their
parent control towers.

2016-06-01 16:34 GMT+02:00 ClaasStoertenbecker <notifications@github.com>:

**Comment by roxlukas** [comment]
**IMPORTANT INFORMATION** My dev laptop has recently suffered a hardware failure*, and because of very tight budget I won't be able to replace it anytime soon. Due to the above fixes will be delayed, but rest assured I haven't given up on LMeve yet.

*) Most likely GPU or Northbridge went up in smoke

**Comment by roxlukas** [comment]
Since Starbases are going to be phased out, this enhancement makes little sense.
