### ISSUE TITLE
Poller has hanged

### ISSUE THREAD

**Issue by ClaasStoertenbecker** [roxlukas/lmeve#35]
Error (Tool): "EVE API Poller has hanged, contact Administrator!"
Error (Run poller.php manually): "PHP Fatal error:  Call to a member function attributes() on string in /var/www/lmeve/bin/libpoller.php on line 73"

**Comment by ClaasStoertenbecker** [comment]
Reinstalled, will observe if the problem occurs a second time.

**Comment by roxlukas** [comment]
I sent you a quick patch to get more information. check your mail please.

**Comment by roxlukas** [comment]
It seems the problem it's not recurring - closing it
