### ISSUE TITLE
Add vagrant script to provision a new server to run lmeve

### ISSUE THREAD

**Issue by TrentBartlem** [roxlukas/lmeve#4]
Even if it's as anaemic as eve_reddit_bot's [Vagrantfile](https://github.com/eveRedditBot/eve_reddit_bot/blob/master/Vagrantfile) + [bootstrap.sh](https://github.com/eveRedditBot/eve_reddit_bot/blob/master/bootstrap.sh), it would be really helpful to have it all in a script.

**Comment by roxlukas** [comment]
Scripts added. It *should* work.
