### ISSUE TITLE
Bug: Messages

### ISSUE THREAD

**Issue by ClaasStoertenbecker** [roxlukas/lmeve#42]
Messages are not displayed properly.
https://gyazo.com/aab4f5b28dedb8be4830e3d1843de3a5

**Comment by roxlukas** [comment]
Please send to my mail contents of the following db tables:
  * messages
  * messages_sent
If you think there is confidential information there, feel free to anonymize it before sending.

**Comment by roxlukas** [comment]
* IMPORTANT INFORMATION * My dev laptop has recently suffered a hardware failure, and because of very tight budget I won't be abel to replace it anytime soon. Due to the above fixes will be delayed, but rest assured I haven't given up on LMeve yet.

**Comment by ClaasStoertenbecker** [comment]
Sent you the email with the tables.
Here a screenshot how it looks like in lmeve.
https://gyazo.com/44a205b77774e7866ae7e8e9b40e8827

**Comment by HunHawk** [comment]
In the apache's log there is a PHP error when try to open messages:
PHP Warning:  include(): Failed opening 'filter.php' for inclusion (include_path='../include') in /var/www/lmeve/include/40.php on line 15

After put it in place (get it from VMware image), a new error appears:
PHP Fatal error:  Redefinition of parameter $zlec_wyk in /var/www/lmeve/include/filter.php on line 30

I removed lines between line 30 and line 43 in filter.php, the inbox window works again.
The working filter.php attached, upload it into /include folder.

[filter.zip](https://github.com/roxlukas/lmeve/files/511280/filter.zip)

**Comment by roxlukas** [comment]
Thanks for fixing the bug, much appreciated!

2016-10-05 15:33 GMT+02:00 HunHawk <notifications@github.com>:
