### ISSUE TITLE
ESI API Compatiblity

### ISSUE THREAD

**Issue by roxlukas** [roxlukas/lmeve#44]
Rewrite poller to use new ESI API. XML and CREST will be preserved for backward compatiblity.

https://community.eveonline.com/news/dev-blogs/introducing-esi/

**Comment by roxlukas** [comment]
After some investigation it turns out ESI does not allow access to corporation data yet, so it is of limited use for LMeve right now. However, switching from Public CREST and eve-central.com for market data would be a good idea.

**Comment by roxlukas** [comment]
Another good thing to implement is a GUI for obtaining ESI token, which would be used to access private corp ESI data as it becomes available.

**Comment by Rayvenhaus** [comment]
Is there any progress in moving over to ESI vs. CREST?

**Comment by Regner** [comment]
Would probably be good to get a list of all the endpoints lmeve needs and track which ones are available or not in ESI.

**Comment by roxlukas** [comment]
This is a good idea but it's step number 3 on my list.

I want to get it right rather than quickly, so I will be rewriting poller from scratch in objective PHP.

Step 1 Add GUI for obtaining esi token using the SSO

Step 2 Modify ssologin.php so it has two modes of operation: login and esi token

Step 3 analyze available endpoints, create esi-db mappings

**Comment by roxlukas** [comment]
Working on it. Step 1 and 2 done. Analysis for step 3 done.

**Comment by roxlukas** [comment]
Wrote brand new poller for ESI in objective PHP. Doing it right this time!

Now slowly adding individual routes.

**Comment by roxlukas** [comment]
Late for XML API cutover, but didn't give up yet...

**Comment by roxlukas** [comment]
Most ESI stuff works now, so closing the issue
