### ISSUE TITLE
importing VM into ESXi 5.0 Harddisk issue

### ISSUE THREAD

**Issue by monasucks** [roxlukas/lmeve#45]
Hi,

when I import the VM into ESXi I got the following issue, if I try to power it up:
Module DevicePowerOn power on failed. 
Unable to create virtual SCSI device for scsi0:0, '/vmfs/volumes/502a6669-dd49db82-eef2-c86000be4342/lmeve/LMeve 0.1.53.vmdk' 
Failed to open disk scsi0:0: Unsupported or invalid disk type 7.  Ensure that the disk has been imported.

**Comment by roxlukas** [comment]
Please use the free VMware Converter application to convert the VM to ESXI format. 

LMeve VM has been set up using desktop product (VMware Player) and might not work on the ESXi, which is Infrastructure product.

Best regards,
Lukas
