### ISSUE TITLE
"ViewKillboard" value missing in table lmrights

### ISSUE THREAD

**Issue by Wildweasel24** [roxlukas/lmeve#47]
Whilst Admin users can see the killboard, no other users or roles can see the killboard or be assigned the role rights, (even if public killboard setting is enabled...?)

Inserted row into lmrights      38, ViewKillboard     issue solved.

Roles can now be assigned the right to view or not the killboard.

**Comment by roxlukas** [comment]
This would also self-resolve with the following config.php option:

$LM_LEARNING_MODE=1;
