### ISSUE TITLE
Buyback

### ISSUE THREAD

**Issue by Rayvenhaus** [roxlukas/lmeve#51]
How do you set up buy back for items you want people to sell to the Corp?

**Comment by roxlukas** [comment]
Go to "Database", search for the item you want to add, open it, tick "Fetch prices" and "Show in buy calc". Both need to be checked for the item to appear on Buy Calc.

You might need to wait for the poller to fetch the prices (up to 60 min on default settings).

Hope it helps.

**Comment by Rayvenhaus** [comment]
Thank you, I'll test this out.

**Comment by Rayvenhaus** [comment]
Yes, that worked, thank you!
