### ISSUE TITLE
API Is Disabled

### ISSUE THREAD

**Issue by Darius-Hutchison** [roxlukas/lmeve#53]
I have tried to synchronize evernus with lmeve, but every time I try it says the API is disabled.  I have generated new keys and checked the northbound api page lmeve does not say that the key has been accessed.

**Comment by roxlukas** [comment]
Please go to "Settings" and find on that page "Enable LMeve Northbound API". Then tick the checbox and click "Save configuration".

Please let me know if that helped :-)

**Comment by Darius-Hutchison** [comment]
Missed that. Thank you for the assistance. Consider it closed.
