### ISSUE TITLE
Northbound TASKS API numbers as strings

### ISSUE THREAD

**Issue by maurerit** [roxlukas/lmeve#55]
Some of the numbers in the TASKS endpoints are coming across as strings in the JSON where as others are numbers:

"name": "Some Person",
"characterID": 1234567,
"typeName": "Some Thing",
"typeID": 1234,
"activityName": "Manufacturing",
"activityID": 1,
"taskID": 2000000,
"runs": 800,
"taskCreateTimestamp": "2018-10-01 00:00:00",
"singleton": 1,
"runsDone": "800",
"jobsDone": 3,
"jobsSuccess": "0",
"jobsCompleted": 0,
"runsCompleted": "200"

The main numbers I'm concerned about here are the runsDone, jobsSuccess and runsCompleted.  I'm tentatively planning some integrations with this endpoint and having them as numbers would be ideal to avoid any funky work arounds to pull them into the primitives that they'll land in.

**Comment by roxlukas** [comment]
This is both PHP's greatest power and greatest weakness: weak typing. And also my failure as a programmer who claims to know and understand these weaknesses. I'll add additional output filters to prevent this.

**Comment by roxlukas** [comment]
Fixed in 9810ad5
