### ISSUE TITLE
suggestion : add tracking options from item detail view into database view 

### ISSUE THREAD

**Issue by dstevens79** [roxlukas/lmeve#60]
creating a faster n easier to manipulate setup that becomes this : 
https://i.imgur.com/UeSCtva.png

the current time and click consuming setup is good if you come across something and want to add it but if your populating a need for new items like a set of salvage etc.. this would make for a lot less clicking and be easier to utilize overall

**Comment by roxlukas** [comment]
Good idea, will implement :-)

**Comment by roxlukas** [comment]
Added in 7580c83
