### ISSUE TITLE
Updating tranquility server status

### ISSUE THREAD

**Issue by dstevens79** [roxlukas/lmeve#69]
[INFORM] Status: Updating tranquility server status...
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /opt/lmeve/bin/Status.php on line 26
[INFORM] Status: Updating singularity server status...
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /opt/lmeve/bin/Status.php on line 26

**Comment by roxlukas** [comment]
Fixed in a212c0d
