### ISSUE TITLE
Enhancement : Group checkboxes to filter the profit chart

### ISSUE THREAD

**Issue by dstevens79** [roxlukas/lmeve#73]
with alot of objects, it can take forever to load this page - however if this page were filtered by a few categories (ships / fittings / drones / other would do just fine) the loading time of this page would be reduced by a factor of immeasurable amounts

**Comment by roxlukas** [comment]
This functionality is within Profit Explorer -> you can basically go between market groups and see how profitable individual items are.

I think it would be possible to switch from invMarketGroups to invGroups to show more general classes (Cruiser) rather than market (Gallente Cruiser)
