### ISSUE TITLE
enhancement : copy and paste market a la evepraisal

### ISSUE THREAD

**Issue by dstevens79** [roxlukas/lmeve#74]
so miners think its great but explorers are like omg i have 700 items... 
so i have been asked to suggest a copy your inventory and paste into the box setup for buybacks
i see the reasoning for this, so i put this together : 

![image](https://user-images.githubusercontent.com/29002807/51208145-d959f800-18da-11e9-8a4f-81cf526eff8e.png)

it could parse and check against items we want to buy and all other items would be 0 isk

**Comment by roxlukas** [comment]
This is currently in development

**Comment by roxlukas** [comment]
Added in 0a03eaf693fc99aaa05e84ddbc214e54f87c0f58
