### ISSUE TITLE
moon ore

### ISSUE THREAD

**Issue by dstevens79** [roxlukas/lmeve#77]
https://i.imgur.com/tG12i0a.png

shimmering ovatite will not show up in the buyback market

also - how do i or would you deal with the rampant and massively off pricing fluctuations that can be seen there?

**Comment by dstevens79** [comment]
i think this is a result of jita not having any buy orders for this material

**Comment by Razeu** [comment]
Both enabled?
![image](https://user-images.githubusercontent.com/12057494/53919601-c823a100-406a-11e9-9d7f-4c2c545abb07.png)

**Comment by zopha** [comment]
For moon ores like this, I only price them by the value of refined materials. This ore is simply too large to be worth shipping to Jita to sell raw.

Ubiquitious
Common
Uncommon
Exceptional
Rare

All of these types have skewed pricing in Jita and usually extremely undervalued raw.
