### ISSUE TITLE
buyback is compounding corp store values and comparing them to the ideal stock value in buyback

### ISSUE THREAD

**Issue by dstevens79** [roxlukas/lmeve#78]
if im doing the math and guesstimating right, when buybaack orders are going in the buyback players are seeing red yellow green for a total of all corp store values and comparing that to a single corp ideal storage amount

is this working as intended?
is there a way to set threshholds for each corp independantly?

**Comment by roxlukas** [comment]
Yes, this is by design. We've used single LMeve instance for three corporations within the same alliance and for one shared industry operation.

**Comment by roxlukas** [comment]
This is working as intended, so, would you mind if I closed this one?
