### ISSUE TITLE
bug / enhancement : more accurate ore valuation

### ISSUE THREAD

**Issue by dstevens79** [roxlukas/lmeve#80]
and after doing some math on what the reported pricing on some ore is especialy null ores ive determined it can be widely skewed in value based on what it should be - largely cause these ores are not existant in jita in large quantities or anywhere really - so .. you end up with buyback orders like this : 
https://i.imgur.com/cYSXQDz.png

after discovering that i started thinking that a process liek this that runs once a day would reduce polling times by removing ore types completely and provide more accurate pricing that a corp would want to pay overall : 

have the server sim-reprocess 100 of each ore and spit back the value.. 
foreach oretype orevalue = materials existing polled combined value / 100 

doing that once a day would remove skewed pricing on what a corp would want to pay for ore buybacks 

got the idea from http://www.eve-cost.eu/reprocessing

**Comment by roxlukas** [comment]
I have an idea to add option under Settings, and if checked it will overwrite ore prices from market with prices calculated according to ore makeup (similar to Ore Value Chart in Database).

**Comment by zopha** [comment]
Looking at the values in the Ore Value Chart the goo parts of the moon goo ores are missing, it looks like they're being valued just on the mineral content. There's a list of their contents here https://ore.cerlestes.de/moon if needed.

**Comment by roxlukas** [comment]
Thanks @zopha , this data is in the SDE, so there's no problem.

Ore Value Chart was created around 2014, when ores only contained minerals, so that page only shows groupID 18 (minerals) in function of categoryID 25 (ores). This will be refactored at the same time as issue #80, because functions calulcating ore value will be shared between Ore Value Chart and for issue #80.

**Comment by Razeu** [comment]
Allow for buyback calc, to have several predefined refinery %to select from,
![image](https://user-images.githubusercontent.com/12057494/53919895-a7a81680-406b-11e9-9294-4ffcac15d99d.png)
As based on comp Im guessing would mean 100% yield
So in short add the option to factor in for refinery % yield
HS 76 or 77%
Low 79 %
0.0 85 % perhaps higher
I cannot verify if above numbers are correct

**Comment by Razeu** [comment]
Getting some real low prices on regular ore...
![image](https://user-images.githubusercontent.com/12057494/54078335-b8a09400-42c6-11e9-8ee6-35b3050da180.png)

**Comment by dstevens79** [comment]
No Rig A	73.8
HS A1		75.3
HS A2		78.2
LS A1		79.8
LS A2		82.9
NS/WH A1	84.3
NS/WH A2	87.6
No Rig T	75.3
HS T1		76.8
HS T2		79.8
LS T1		81.4
LS T2		84.6
NS/WH T1	86
NS/WH T2	89.3

**Comment by dstevens79** [comment]
there do seem to be some ores not properly populating - they tend to be at the top or next to the top of the list - i had assumed my delayed marketing polling was causing this - but not so much

**Comment by roxlukas** [comment]
Functionality added in 6b65e4f
